from langchain_community.retrievers import WikipediaRetriever

retriever = WikipediaRetriever(top_k_results=5,lang="en")

query = "geopolitical history of India and Pakistan China perspective"

docs = retriever.invoke(query)


for i,doc in enumerate(docs):
    print(f"\n-----Result{i+1}----------")
    print(f"Content : {doc.page_content}.... ")

# -----Result1----------
# Content : The history of the Islamic Republic of Pakistan began on 14 August 1947 when the country came into being in the form of the Dominion of Pakistan within the British Commonwealth as the result of the Pakistan Movement and the partition of India. While the history of the Pakistani nation according to the Pakistan government's official chronology started with the Islamic rule over Indian subcontinent by Muhammad ibn al-Qasim which reached its zenith during Mughal era. In 1947, Pakistan consisted of West Pakistan (today's Pakistan) and East Pakistan (today's Bangladesh). The President of All-India Muslim League and later the Pakistan Muslim League, Muhammad Ali Jinnah became Governor-General while the secretary general of the Muslim League, Liaquat Ali Khan became Prime Minister. The constitution of 1956 made Pakistan an Islamic democratic country.     
# Pakistan faced a civil war and Indian military intervention in 1971 resulting in the secession of East Pakistan as the new country of Bangladesh. The country has also unresolved territorial disputes with India, resulting in four conflicts. Pakistan was closely tied to the United States in the Cold War. In the Afghan–Soviet War, it supported the Afghan mujahideen and played a vital role in the defeat of Soviet Forces and forced them to withdraw from Afghanistan. The country continues to face challenging problems including terrorism, poverty, illiteracy, corruption and political instability. Terrorism due to war on terror damaged the country's economy and infrastructure to a great extent from 2001 to 2009 but Pakistan is once again developing.   
# Pakistan is a nuclear power as well as a declared nuclear-weapon state, having conducted six nuclear tests in response to five nuclear tests of their rival Republic of India in May 1998. The first five tests were conducted on 28 May and the sixth one on 30 May. With this status, Pakistan is seventh in world, second in South Asia and the only country in the Islamic World. Pakistan also has the sixth-largest standing armed forces in the world and is spending a major amount of its budget on defense. Pakistan is the founding member of the OIC, the SAARC and the Islamic Military Counter Terrorism Coalition as well as a member of many international organisations including the UN, the Shanghai Cooperation Organisation, the Commonwealth of Nations, the ARF, the Economic Cooperation Organization and many more.
# Pakistan is a middle power which is ranked among the emerging and growth-leading economies of the world and is backed by one of the world's largest and fastest-growing middle class. It has a semi-industrialized economy with a well-integrated agriculture sector. It is identified as one of the Next Eleven, a group of eleven countries that, along with the BRICs, have a high potential to become the world's largest economies in the 21st century. Although Pakistan faced a severe economic crisis from 2022 to 2024, geographically Pakistan is an important country and a source of contact between Middle East, Central Asia, South Asia and East Asia.


# == Pakistan Movement ==

# Important leaders in the Muslim League highlighted that Pakistan would be a "New Madinah", in other words the second Islamic state established after the Prophet Muhammad's creation of an Islamic state of Madinah which was later developed into Rashidun Caliphate. Pakistan was popularly envisaged as an Islamic utopia, a successor to the defunct Islamic Caliphate and a leader and protector of the entire Islamic world. Islamic scholars debated over whether it was possible for the proposed Pakistan to truly become an Islamic state.
# Another motive and reason behind the Pakistan Movement and Two Nation Theory is the ideology of pre-partition Muslims and leaders of Muslim League including Muhammad Ali Jinnah and Allama Iqbal is that, to re-establish the Muslim rule in South Asia. Once Jinnah said in his speech:

# The Pakistan Movement started when the first Muslim (Muhammad bin Qasim) put his foot on t....

# -----Result2----------
# Content : The United States has been providing military aid and economic assistance to Pakistan for various purposes since 1948. In 2017, the U.S. stopped military aid to Pakistan, which was about US$2 billion per year. With U.S. military assistance suspended in 2018 and civilian aid reduced to about $300 million for 2022, Pakistani authorities have turned to other countries for help.


# == History ==
# From 1947 to 1958, under civilian leadership, the United States provided Pakistan with modest economic aid and limited military assistance. During this period, Pakistan became a member of the South East Asian Treaty Organization (SEATO) and the Central Treaty Organization (CENTO), after a Mutual Defence Assistance Agreement signed in May 1954, which facilitated increased levels of both economic and military aid from the U.S.
# In 1958, Ayub Khan led Pakistan's first military coup, becoming Chief Martial Law Administrator (CMLA) and later President until 1969. During his tenure, the U.S. delivered substantial economic and military aid, despite Pakistan's governance by military regime, and amidst events like the Indo-Pakistani war of 1965.
# Yahya Khan succeeded Ayub in 1969, holding power during the Indo-Pakistani war of 1971 which led to the secession of East Pakistan and the formation of Bangladesh. Under Yahya, the U.S. provided adequate economic but minimal military aid.
# Civilian governance of Zulfikar Ali Bhutto resumed from 1971 to 1977, during which the U.S. offered modest economic support and withheld military aid as Pakistan finalized its constitution, establishing a parliamentary democracy.   
# Following another military coup in 1977, Muhammad Zia-ul-Haq led the country. In April 1979, President Jimmy Carter halted all aid, excluding food assistance, due to Pakistan's efforts to establish a uranium enrichment facility, following Symington Amendment. Initial U.S. aid was limited, increasing significantly after geopolitical shifts such as the Soviet invasion of Afghanistan in 1979 and the fall of the Shah of Iran. U.S. sanctions imposed in April 1979 due to Pakistan's nuclear activities were lifted by the end of the year in light of these events.
# Between 1988 and 1999, under civilian and democratic governments, U.S. aid was low, particularly after the Soviet withdrawal from Afghanistan in 1989. The aid was suspended in the 1990s under President George H. W. Bush, who cited concerns over Pakistan's developing nuclear program. Relations between the two countries deteriorated as the U.S. implemented the Pressler Amendment. This amendment led to severe sanctions against Pakistan, exacerbating economic challenges for the country's nascent civilian government. Consequently, all forms of bilateral aid from the U.S. to Pakistan were halted. The once expansive operations of the U.S. Agency for International Development (USAID) in Pakistan, which had employed over 1,000 staff across the country, were dramatically reduced almost overnight. Further complications arose from U.S. sanctions following Pakistan's nuclear tests in 1998, which were conducted in response to similar tests by India.
# The return of military rule under Pervez Musharraf from 1999 to 2008 initially saw little U.S. economic or military aid. However, following the September 11, 2001 attacks, all U.S. sanctions were removed, and Pakistan, having aligned with the U.S. in the war on terror, received substantial increases in both economic and military assistance.      
# On June 16, 2009, the U.S. Senate Foreign Relations Committee passed the Enhanced Partnership with Pakistan Act of 2009, commonly referred to as the Kerry-Lugar Bill. The bipartisan act authorized an annual provision of $1.5 billion in U.S. aid to Pakistan, aimed at fostering enhanced bilateral relations.
# In 2011, the Obama administration suspended more than one-third of all military assistance, totaling approximately $800 million due to Osama bin Laden-related controversy. This reduction encompassed funds designated for military h....

# -----Result3----------
# Content : The India–Pakistan war of 1971, also known as the third Indo-Pakistani war, was a military confrontation between India and Pakistan that occurred during the Bangladesh Liberation War in East Pakistan from 3 December 1971 until the Pakistani capitulation in Dhaka on 16 December 1971.  The war began with Pakistan's Operation Chengiz Khan, consisting of preemptive aerial strikes on eight Indian air stations. The strikes led to India declaring war on Pakistan, marking their entry into the war for East Pakistan's independence, on the side of Bengali nationalist forces. India's entry expanded the existing conflict with Indian and Pakistani forces engaging on both the eastern and western fronts.
# Thirteen days after the war started, India achieved a clear upper hand, and the Eastern Command of the Pakistan military signed the instrument of surrender on 16 December 1971 in Dhaka, marking the formation of East Pakistan as the new nation of Bangladesh. Approximately 93,000 Pakistani servicemen were taken prisoner by the Indian Army, which included 79,676 to 81,000 uniformed personnel of the Pakistan Armed Forces, including some Bengali soldiers who had remained loyal to Pakistan. The remaining 10,324 to 12,500 prisoners were civilians, either family members of the military personnel or collaborators (Razakars).
# It is estimated that members of the Pakistani military and supporting pro-Pakistani Islamist militias killed between 300,000 and 3,000,000 civilians in Bangladesh. As a result of the conflict, a further eight to ten million people fled the country to seek refuge in India.
# During the war, members of the Pakistani military and supporting pro-Pakistani Islamist militias called the Razakars raped between 200,000 and 400,000 Bangladeshi women and girls in a systematic campaign of genocidal rape.


# == Background ==

# The Indo-Pakistani conflict was sparked by the Bangladesh Liberation War, which was a result of the violation of the rights of East Pakistan by the Pakistan Army. The political tensions in East Pakistan had its origin in the creation of Pakistan as a result of the partition of India by the United Kingdom in 1947; the popular language movement in 1950; mass riots in East Bengal in 1964; and the mass protests in 1969. These led to the resignation of President Ayub Khan, who invited army chief General Yahya Khan to take over the central government. The geographical distance between the eastern and western wings of Pakistan was vast; East Pakistan lay over 1,600 kilometres (1,000 mi) away, which greatly hampered any attempt to integrate the Bengali and the Pakistani cultures.
# To overcome the Bengali domination and prevent formation of the central government in Islamabad, the controversial One Unit programme established the two wings of East and West Pakistan. West Pakistanis' opposition to these efforts made it difficult to effectively govern both wings. In 1969, President Yahya Khan announced the first general elections and disestablished the status of West Pakistan as a single province in 1970, in order to restore it to its original heterogeneous status comprising four provinces, as defined at the time of establishment of Pakistan in 1947. In addition, there were religious and racial tensions between Bengalis and the multi-ethnic West Pakistanis, as Bengalis looked different from the dominant West Pakistanis.     
# The East Pakistan's Awami League leader Sheikh Mujibur Rahman stressed his political position by presenting his Six Points and endorsing the Bengalis' right to govern themselves. The 1970 Pakistani general election, resulted in Awami League gaining 167 out of 169 seats for the East Pakistan Legislative Assembly, and a near-absolute majority in the 313-seat National Assembly, while the vote in West Pakistan was mostly won by the socialist Pakistan Peoples Party. The League's election success caused many West Pakistanis to fear that it would allow the Bengalis to draft the constitution based on the Six Points and liberalism....     

# -----Result4----------
# Content : Since the partition of British India in 1947 and subsequent creation of the dominions of India and Pakistan, the two countries have been involved in a number of wars, conflicts, and military standoffs. A long-running dispute over Kashmir and cross-border terrorism have been the predominant cause of conflict between the two states, with the exception of the Indo-Pakistani War of 1971, which occurred as a direct result of hostilities stemming from the Bangladesh Liberation War in erstwhile East Pakistan (now Bangladesh).


# == Background ==

# The Partition of India came in 1947 with the sudden grant of independence. It was the intention of those who wished for a Muslim state to have a clean partition between independent and equal "Pakistan" and "Hindustan" once independence came.
# Nearly one third of the Muslim population of India remained in the new India.
# Inter-communal violence between Hindus, Sikhs and Muslims resulted in between 200,000 and 2 million casualties leaving 14 million people displaced.
# Princely states in India were provided with an Instrument of Accession to accede to either India or Pakistan.       


# == Wars ==


# === Indo-Pakistani war of 1947–1948 ===

# The war, also called the first Indo-Pakistani war, started in October 1947 when Pakistan feared that the Maharaja of the princely state of Kashmir and Jammu would accede to India. Following partition, princely states were left to choose whether to join India or Pakistan or to remain independent. Jammu and Kashmir, the largest of the princely states, had a majority Muslim population and significant fraction of Hindu population, all ruled by the Hindu Maharaja Hari Singh. Tribal Islamic forces with support from the army of Pakistan attacked and occupied parts of the princely state forcing the Maharaja to sign the Instrument of Accession of the princely state to the Dominion of India to receive Indian military aid. The UN Security Council passed Resolution 47 on 22 April 1948. The fronts solidified gradually along what came to be known as the Line of Control. A formal cease-fire was declared at 23:59 on the night of 1 January 1949. India gained control of about two-thirds of the state (Kashmir Valley, Jammu and Ladakh) whereas Pakistan gained roughly a third of Kashmir (Azad Kashmir, and Gilgit-Baltistan). The Pakistan controlled areas are collectively referred to as Pakistan administered Kashmir.     


# === Indo-Pakistani war of 1965 ===

# This war started following Pakistan's Operation Gibraltar, which was designed to infiltrate forces into Jammu and Kashmir to precipitate an insurgency against rule by India. India retaliated by launching a full-scale military attack on West Pakistan. The seventeen-day war caused thousands of casualties on both sides and witnessed the largest engagement of armored vehicles and the largest tank battle since World War II. The hostilities between the two countries ended after a ceasefire was declared following diplomatic intervention by the Soviet Union and USA and the subsequent issuance of the Tashkent Declaration. India had the upper hand over Pakistan when the ceasefire was declared.    


# === Indo-Pakistani war of 1971 ===

# This war was unique in the way that it did not involve the issue of Kashmir, but was rather precipitated by the crisis created by the political battle brewing in erstwhile East Pakistan (now Bangladesh) between Sheikh Mujibur Rahman, Leader of East Pakistan, and Yahya Khan and Zulfikar Ali Bhutto, leaders of West Pakistan. This would culminate in the declaration of Independence of Bangladesh from the state system of Pakistan. Following Operation Searchlight and the 1971 Bangladesh atrocities, about 10 million Bengalis in East Pakistan took refuge in neighbouring India.     
# India intervened in the ongoing Bangladesh liberation movement. After a large scale pre-emptive strike by Pakistan, full-scale hostilities between the two countries commenced.
# Pakistan attacked at several places along India's western border with Pakistan, but th....

# -----Result5----------
# Content : China–Pakistan Economic Corridor (CPEC; Chinese: 中巴经济走廊; pinyin: Zhōng bā jīngjì zǒuláng; Urdu: چین پاکستان اقتصادی راہداری) is a 3,000 km Chinese infrastructure network project currently under construction in Pakistan. This sea-and-land-based corridor aims to secure and shorten the route for China’s energy imports from the Middle East, avoiding the existing path through the Straits of Malacca between Malaysia and Indonesia, which could be blockaded in case of war, thereby threatening China’s energy-dependent economy. Developing a deep-water port at Gwadar in the Arabian Sea and establishing a robust road and rail network from this port to the Xinjiang region in western China would serve as a shortcut, enhancing trade between Europe and China. In Pakistan, the project aims to address electricity shortages, develop infrastructure, and modernize transportation networks, while also transitioning the economy from an agriculture-based structure to an industrial one.
# CPEC is seen as the main plank of China's Belt and Road Initiative, and as of early 2024, is the BRI's most developed land corridor. CPEC's potential impact on Pakistan has been compared to that of the Marshall Plan, undertaken by the United States in post-war Europe.
# Following the proposal by Chinese Premier Li Keqiang in 2013, the operationalization of CPEC is expected to reduce the existing 12,000 km journey for oil transportation to China to 2,395 km. This is estimated to save China $2 billion per year. China had already acquired control of Gwadar Port on 16 May 2013. Originally valued at $46 billion, the value of CPEC projects was $62 billion as of 2020. By 2022, Chinese investment in Pakistan had risen to $65 billion. China refers to this project as the revival of the Silk Road. CPEC envisages rapidly upgrading Pakistan's infrastructure and thereby strengthening its economy by constructing modern transportation networks, numerous energy projects, and special economic zones.
# The potential industries being set up in the CPEC special economic zones include food processing, cooking oil, ceramics, gems and jewelry, marble, minerals, agriculture machinery, iron and steel, motorbike assembling, electrical appliances, and automobiles.


# == History ==


# === Background ===
# Plans for a corridor stretching from the Chinese border to Pakistan's deepwater ports on the Arabian Sea date back to the 1950s and motivated the construction of the Karakoram Highway beginning in 1959. Chinese interest in Pakistan's deep-water harbor at Gwadar was rekindled in 2002, leading to construction at Gwadar port, which was completed in 2006. Expansion of Gwadar Port then ceased due to political instability in Pakistan following the fall of General Pervez Musharraf and the subsequent conflict between the Pakistani state and Taliban militants.
# Since the early 1990s, the IMF has provided more than a dozen bailouts to Pakistan to save its dwindling economy, which has struggled for 22 of the past 30 years to meet the austerity measures demanded by the IMF. Nadeem-ul-Haque, a former IMF official and former deputy chairman of the Pakistani government's Planning Commission, wrote, "The pattern is always the same. With the Fund's blessing, the government goes on a shopping spree, taking out costly loans for expensive projects, thus building up even more debt and adding new inefficiencies. After a few years, another crisis ensues, and it is met by another IMF program." The Pakistani establishment views Chinese loans as an alternative to IMF loans.
# In 2013, then Pakistani President Asif Ali Zardari and Chinese Premier Li Keqiang decided to further enhance mutual connectivity. A memorandum of understanding on cooperation for a long-term plan for the China–Pakistan Economic Corridor was signed by Xu Shao Shi and Shahid Amjad Chaudhry. 
# In February 2014, Pakistani President Mamnoon Hussain visited China to discuss plans for an economic corridor in Pakistan. Two months later, Pakistani Prime Minister Nawaz Shar....